### ISSUE TITLE
Modal Not Displaying on Smaller Devices

### ISSUE THREAD

**Issue by stevepop** [Innologica/vue-components#1]
Hi,

Thanks for the work you are doing here. I noticed that on smaller screens, your modals don't show at all.

See image below;
<img width="381" alt="iphone5_screen" src="https://cloud.githubusercontent.com/assets/526063/21564945/ba8728f0-ce89-11e6-86a9-6bc20372bfea.png">

I was able to make it work by creating media queries with the following;
```
.modal-container.side-panel {
    position: relative; 
}
```

**Comment by nkostadinov** [comment]
Thank you for your feedback @stevepop . I added media query for small screens in the CSS.
The components are still work in progress so you may encounter some problems.
